const $=s=>document.querySelector(s), audio=$('#audio');let catalog=[],flat=[],idx=-1,lastSave=0;
const fmt=s=>{if(!isFinite(s))return'0:00';s=Math.max(0,Math.floor(s));return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
async function init(){const data=await fetch(`catalog.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>r.json());catalog=data.specialties;render();restore();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=4',{updateViaCache:'none'});}
function render(){const root=$('#library');root.innerHTML='';flat=[];let total=0;catalog.forEach((sp,si)=>{const box=document.createElement('section');box.className='specialty';box.style.setProperty('--accent',sp.color||'#3378a4');const lessons=sp.lessons||[];total+=lessons.length;box.innerHTML=`<div class="specialty-head" role="button" tabindex="0" aria-expanded="${si===0}"><div class="specialty-name"><span class="specialty-dot"></span><strong>${sp.title}</strong></div><div class="specialty-meta"><span>${lessons.length} aulas</span><b class="chevron">⌄</b></div></div><div class="lessons${si===0?'':' collapsed'}"></div>`;const head=box.querySelector('.specialty-head'),list=box.querySelector('.lessons');const toggle=()=>{const closed=list.classList.toggle('collapsed');head.setAttribute('aria-expanded',String(!closed));box.classList.toggle('is-collapsed',closed)};head.onclick=toggle;head.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}};lessons.forEach(l=>{const i=flat.length;flat.push({...l,specialty:sp.title,color:sp.color});const row=document.createElement('div');row.className='lesson';row.innerHTML=`<div class="num">${String(l.number).padStart(2,'0')}</div><div><strong>${l.title}</strong><small>${l.comingSoon?'Em preparação':(l.duration||'Áudio disponível')}</small></div><button aria-label="${l.comingSoon?'Em preparação':'Reproduzir'}">${l.comingSoon?'…':'▶'}</button>`;if(!l.comingSoon)row.onclick=()=>load(i,true);list.appendChild(row)});root.appendChild(box)});$('#count').textContent=`${total} aulas`;}
function load(i,autoplay=false){if(i<0||i>=flat.length||flat[i].comingSoon)return;idx=i;const l=flat[i];audio.src=l.audio;$('#nowSpecialty').textContent=l.specialty.toUpperCase();$('#nowTitle').textContent=l.title;$('#player').classList.remove('hidden');const saved=JSON.parse(localStorage.getItem('tepProgress')||'{}')[l.audio];audio.onloadedmetadata=()=>{if(saved&&saved<audio.duration-10)audio.currentTime=saved;update();if(autoplay)audio.play().catch(()=>{})};localStorage.setItem('tepLast',JSON.stringify({i,title:l.title}));updateResume();}
function save(){if(idx<0)return;const p=JSON.parse(localStorage.getItem('tepProgress')||'{}');p[flat[idx].audio]=audio.currentTime;localStorage.setItem('tepProgress',JSON.stringify(p));}
function update(){if(audio.duration){$('#seek').value=Math.round(audio.currentTime/audio.duration*1000);$('#duration').textContent=fmt(audio.duration)}$('#current').textContent=fmt(audio.currentTime);$('#play').textContent=audio.paused?'▶':'❚❚';if(Date.now()-lastSave>3000){save();lastSave=Date.now()}}
function updateResume(){const last=JSON.parse(localStorage.getItem('tepLast')||'null');if(last&&flat[last.i]&&!flat[last.i].comingSoon){$('#resume').classList.remove('hidden');$('#resumeTitle').textContent=last.title;$('#resumeBtn').onclick=()=>load(last.i,true)}}
function restore(){updateResume();document.querySelector('[data-speed="1"]').classList.add('active')}
$('#play').onclick=()=>audio.paused?audio.play():audio.pause();$('#back').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-15);$('#forward').onclick=()=>audio.currentTime=Math.min(audio.duration||0,audio.currentTime+15);$('#prev').onclick=()=>load(idx-1,true);$('#next').onclick=()=>load(idx+1,true);$('#seek').oninput=e=>{if(audio.duration)audio.currentTime=e.target.value/1000*audio.duration};$('#closePlayer').onclick=()=>$('#player').classList.add('hidden');document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{audio.playbackRate=+b.dataset.speed;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});audio.ontimeupdate=update;audio.onplay=update;audio.onpause=()=>{update();save()};audio.onended=()=>{save();let n=idx+1;while(n<flat.length&&flat[n].comingSoon)n++;if(n<flat.length)load(n,true)};window.addEventListener('beforeunload',save);init();